import type { Metadata } from "next";

import {Inter, Playfair_Display, Cabin} from "next/font/google";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter_init = Inter({
 weight:["400"],
 subsets:["latin"],
 variable:"--font-inter",
});

const playfair_display_init = Playfair_Display({
  weight:["400"],
  subsets:["latin"],
    variable:"--font-playfair_display",
  
})


const cabin_init = Cabin({
  weight:["500"],
  subsets:["latin"],
    variable:"--font-cabin",
  
})



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= {`${inter_init.variable} ${playfair_display_init.variable} ${cabin_init.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
